language: node_js
node_js:
  - "stable"
cache: npm
script:
  - npm run travis
before_deploy:
  - git config --local user.name "isgales"
  - git config --local user.email "alkalayg@post.bgu.ac.il"


install:
  - npm ci


#deploy:



# before_install:
# install:
# before_script:
# script:
# after_success:
# after_failure:
# before_deploy:
# deploy:
# after_deploy: